services:
  database:
    image: postgres:18
    container_name: gostructure-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: gostructure
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "25432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      # To mount to a specific host directory, comment out the line above and uncomment one of these:
      # - ${HOME}/var/gostructure_db:/var/lib/postgresql  # should use this on Linux server to preserve data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 1s
      timeout: 1s
      retries: 20
      start_period: 2s

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gostructure-app
    restart: unless-stopped
    ports:
      - "20808:20808"
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_DB: gostructure
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      LISTENING_PORT: 20808
    depends_on:
      database:
        condition: service_healthy

volumes:
  db_data:
